/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as ReportsAssessmentIdRouteImport } from './routes/reports.$assessmentId'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as AssessmentsNewRouteImport } from './routes/assessments.new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const ReportsAssessmentIdRoute = ReportsAssessmentIdRouteImport.update({
  id: '/$assessmentId',
  path: '/$assessmentId',
  getParentRoute: () => ReportsRoute,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientsRoute,
} as any)
const AssessmentsNewRoute = AssessmentsNewRouteImport.update({
  id: '/assessments/new',
  path: '/assessments/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients': typeof PatientsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/patients/$id': typeof PatientsIdRoute
  '/reports/$assessmentId': typeof ReportsAssessmentIdRoute
  '/patients/': typeof PatientsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/patients/$id': typeof PatientsIdRoute
  '/reports/$assessmentId': typeof ReportsAssessmentIdRoute
  '/patients': typeof PatientsIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients': typeof PatientsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/assessments/new': typeof AssessmentsNewRoute
  '/patients/$id': typeof PatientsIdRoute
  '/reports/$assessmentId': typeof ReportsAssessmentIdRoute
  '/patients/': typeof PatientsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/assessments/new'
    | '/patients/$id'
    | '/reports/$assessmentId'
    | '/patients/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/assessments/new'
    | '/patients/$id'
    | '/reports/$assessmentId'
    | '/patients'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/assessments/new'
    | '/patients/$id'
    | '/reports/$assessmentId'
    | '/patients/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AssessmentsNewRoute: typeof AssessmentsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/reports/$assessmentId': {
      id: '/reports/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/reports/$assessmentId'
      preLoaderRoute: typeof ReportsAssessmentIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/assessments/new': {
      id: '/assessments/new'
      path: '/assessments/new'
      fullPath: '/assessments/new'
      preLoaderRoute: typeof AssessmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PatientsRouteChildren {
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsIdRoute: PatientsIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsAssessmentIdRoute: typeof ReportsAssessmentIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsAssessmentIdRoute: ReportsAssessmentIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsRoute: PatientsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AssessmentsNewRoute: AssessmentsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
